### ISSUE TITLE
Optimizing derivative of observable

### ISSUE THREAD

**Issue by ahjanee** [ICB-DCM/pyPESTO#1048]
Hello,

I have an ODE-model and some data that I am importing using the petab format. I would now like to optimize the time derivatives of the observable and the measurement in my problem: given some simulation y(t) and measurement m(t),  I want to find the parameters that minimize the distance between dy/dt and dm/dt. 

I have tried looking into customizing the objective function but I could not figure it out. What would be the easiest way of implementing this?

Thank you!

**Comment by dilpath** [comment]
Perhaps the easiest thing to do would be to replace the observables $y$ in your PEtab observables table with their $\frac{dy}{dt}$ expressions (you could open your model in COPASI and check the $\frac{dx}{dt}$ expressions, to substitute them into your observables), and change your time series measurements to be e.g. $\frac{y_2-y_1}{t_2-t_1}$ for consecutive measurements (central differences might be better).

If you want to fit the time derivatives because you don't want the initial condition to contribute to the training, then estimating the initial condition might also achieve this.

If you're fitting relative data, you could use pyPESTO's hierarchical optimization to efficiently compute scaling and offset parameters on the observables. e.g.: https://github.com/ICB-DCM/pyPESTO/blob/main/doc/example/hierarchical.ipynb

If none of the above, I would be curious to know why you're trying to fit time derivatives, if you're able to share! Otherwise, you're welcome to ask for further advice.

**Comment by ahjanee** [comment]
Thank you for the quick reply. I have tried to replace the observables as you suggested. The derivative depends on another state ($R$),  a parameter (which is part of the estimation) ($N$) and a time-dependend function ($k_F(t,a_1,...,a_m)$)  defined in the model: $\frac{dX}{dt} = N \cdot k_F(t,a_1,...,a_m) \cdot R(t)$. If I put this expression as observableFormula, I get this error
 

> Traceback (most recent call last):
  File "/home/htc/bzfernsa/PMU3/optimization.py", line 56, in <module>
    importer = pypesto.petab.PetabImporter(petab_problem)
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/pypesto/petab/importer.py", line 91, in __init__
    if petab.lint_problem(petab_problem):
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/petab/lint.py", line 797, in lint_problem
    check_condition_df(problem.condition_df, problem.model,
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/petab/lint.py", line 125, in check_condition_df
    allowed_cols |= set(petab.get_output_parameters(
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/petab/observables.py", line 98, in get_output_parameters
    free_syms = sorted(sp.sympify(formula).free_symbols,
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/core/sympify.py", line 496, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 1101, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 1092, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
  File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 907, in eval_expr
    expr = eval(
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'function' and 'kF'

When I omit the function and only write an expression for  $\frac{dX}{dt} = N \cdot R(t)$ I get 

> ValueError: Error from parse_expr with transformed code: "N *Symbol ('R' )"
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/htc/bzfernsa/PMU3/optimization.py", line 56, in <module>
>     importer = pypesto.petab.PetabImporter(petab_problem)
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/pypesto/petab/importer.py", line 91, in __init__
>     if petab.lint_problem(petab_problem):
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/petab/lint.py", line 797, in lint_problem
>     check_condition_df(problem.condition_df, problem.model,
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/petab/lint.py", line 125, in check_condition_df
>     allowed_cols |= set(petab.get_output_parameters(
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/petab/observables.py", line 98, in get_output_parameters
>     free_syms = sorted(sp.sympify(formula).free_symbols,
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/core/sympify.py", line 496, in sympify
>     expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 1101, in parse_expr
>     raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 1092, in parse_expr
>     rv = eval_expr(code, local_dict, global_dict)
>   File "/home/htc/bzfernsa/miniconda3/envs/py39/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 907, in eval_expr
>     expr = eval(
>   File "<string>", line 1, in <module>
> TypeError: unsupported operand type(s) for *: 'function' and 'Symbol'

N is defined both in the model and in the parameters.tsv file. Maybe there is a specific kind of syntax I need to use that I am not aware of? 

I am interested in the derivative because our application (neurotransmission processes) demands for it. Basically, our model gives a cumulated sum of the vesicular releases that happen and I want to look at the non-cumulated release events.

**Comment by dilpath** [comment]
Thankfully this just looks like a formatting issue. Here are some suggestions.

- if $R$ is some state variable in your model (species in your SBML), then just use `R` instead of `R(t)` in your formula
- use the expression for $k_F$, instead of the symbol

 e.g. if $k_F(...) = t a_1 a_2$ in your model, then specify your observable formula as
```
N * (t * a_1 * a_2) * R
```

If you don't like the idea of defining $k_F$ or $\frac{dX}{dt}$ in both your SBML model and the PEtab observables table, you could avoid this by creating some SBML assignment rule like `dX_dt_rhs = N * k_F(...) * R`, then change $\frac{dX}{dt}$ to be `dX_dt = dX_dt_rhs` and set the PEtab observables formula to be just `dX_dt_rhs`. However, if your model is defined in terms of SBML reactions, rather than SBML assignment/rate rules, this might make things more complicated.

> I am interested in the derivative because our application (neurotransmission processes) demands for it. Basically, our model gives a cumulated sum of the vesicular releases that happen and I want to look at the non-cumulated release events.

Cool, thanks!

**Comment by ahjanee** [comment]
Sure, I am attaching the files. 
[ModelUpload.zip](https://github.com/ICB-DCM/pyPESTO/files/11222484/ModelUpload.zip)

**Comment by dilpath** [comment]
I think the issue might just be in naming. SymPy is used for some symbolic computations, and automatically converts `N` to a "function". Renaming your variables to have longer names that don't conflict with common mathematical function names (e.g. not `exp`) might resolve the issue, or simply prepend them with an underscore. This appears to be an issue with the PEtab python library -- you could also raise an issue there.

```python
>>> import sympy as sp
>>> sp.sympify("N")
<function N at 0x7f1404ffbee0>
>>> sp.sympify("R")
R
```

**Comment by ahjanee** [comment]
Thank you so much, that helped!

**Comment by dweindl** [comment]
Seems to be resolved. The issue with `N` as identifier has been fixed in https://github.com/PEtab-dev/libpetab-python/pull/202.
