### ISSUE TITLE
petab export

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#109]
Any plans to implement an export? Would be helpful for explicit specification of settings in an automated pipeline.

**Comment by yannikschaelte** [comment]
what do you mean by export? petab -> pypesto quite far already, in the other direction basic writing of result data in the petab format as well (basically).

concerning settings: e.g. optimization and simulation settings are also planned to be specified in the petab format (as far as that is possible).

**Comment by dweindl** [comment]
> concerning settings: e.g. optimization and simulation settings are also planned to be specified in the petab format (as far as that is possible).

Yeah, I think that will be quite difficult. I think that would not be part of PEtab, but rather a custom pyPESTO/AMICI thing. Not sure if that can be generalized very well, looking at the quite different available options for simulators and optimizers.

**Comment by yannikschaelte** [comment]
yes, currently it also looks also more like separate options files for the simulators/samplers used, as one generic one might be too much overhead.

having a format for specifying options (in the first place for amici+pypesto) would also be helpful for distributed computing, and in order to be easily able to (re-)create a model and an analysis. this could also be based on a (python) script that is serialized instead of an options file, but the details will need to be figured out yet.

**Comment by dweindl** [comment]
Closing in favor of #117, which seems to refer to the same thing.
