### ISSUE TITLE
Interpreting the Profile

### ISSUE THREAD

**Issue by cataschlott** [ICB-DCM/pyPESTO#1496]
Hi, I am currently writing my master thesis and used PyPesto for parameter estimation. In the last step of my analysis, I want to include identifiability analysis and therefore analyse the profile. However, I have difficulties interpreting the results. When I plot the profiles using the bounds, for some parameters the peak is visible, as shown in the  [documentation](https://pypesto.readthedocs.io/en/latest/example/getting_started.html#4.-Uncertainty-quantification). For some parameters there is only a line visible, however, when I use the unbounded I can see a clear maximum for these parameters. Does that mean this parameter is identifiable? 

For example the parameters vmax_A1, Km_A1, vmax_A1_2 all show a clear maximum in the second plot (including bounds) but that clear maximum is not visible in the plot with the bounds. 
![pl_run0_bounds](https://github.com/user-attachments/assets/a6b0c5c5-5a84-4818-9625-4f148fc63bfa)

![pl_run0_no_bounds](https://github.com/user-attachments/assets/0ebe9350-bbd7-4d6c-81da-cbe36cea676e)

Thanks for you help!

**Comment by dweindl** [comment]
Hi @cataschlott, these profiles look horrible and I would not recommend deriving any conclusion from any of those. Unfortunately, the current implementation does not perform well in many non-trivial applications. Some improvements are on the way. Maybe you want to give it another try using the code from https://github.com/ICB-DCM/pyPESTO/pull/1447 (`pip3 install git+https://github.com/ICB-DCM/pyPESTO.git@change_profiling#egg=pypesto`).

**Comment by Doresic** [comment]
Hi @cataschlott,
I'll add a bit more detail that might be helpful on top of what @dweindl has already proposed.

The PR with improved profiling should be merged soon, and a new version released. But, as @dweindl suggested, you can already access it and try it out. When using it, I would recommend adding `whole_path=True` in the ProfileOptions object you pass to get a profile of the whole parameter space rather than just a peak.

When visualizing it, you can use `quality_colors=True` to be a bit more insight into what kind of steps the profiling is taking. The main benefit of this is knowing when the profiling code resampled the next step (green dots). That can happen if it is difficult to traverse along the profiling path. I think this is what's happening with your profiles currently. The model is hard to simulate at the first step, so the point is resampled and it (naturally) has a much worse likelihood. If the likelihood ratio is below some value, profiling stops. In most cases, these will result in underestimated confidence intervals.

So:
- try out the new code if you want
- using whole_path=True and quality_colors=True should give more information
