### ISSUE TITLE
Increase max columns to 79

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#22]
Can we increase the max linewidth in flake to something a bit more reasonable like 120 columns?
max 79 really makes me feel claustrophobic.

**Comment by yannikschaelte** [comment]
i'd be fine with 120.
one can do that as described in http://flake8.pycqa.org/en/2.6.0/config.html
however, note that the official pyhton style guide PEP 8 recommends the 79 max line width limit: https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by FFroehlich** [comment]
let's leave it at 79.

**Comment by paulstapor** [comment]
The 79 characters restriction dates back to times in which screen had 640 x 480 pixels and had at most 14''. Sorry, but imho that's simply not up to date, no matter PEP 8. It feels like supporting FORTRAN77 standards...

But there's another real reason to extend this 79 characters thing:
In some functions like in profiling, we have many nested loops and if's, hence indentations. If now an "if"-statements starts at column 21 is is longish (which may happen), I will have a line break (and an indentation) in the "if"-line. In this case, Flake8 throws an error, because the next logic line has the same indentation level as the last "if"-line, which is not good.
Hence, I have literally no possibility to satisfy the Flake8-code-check, as indentation and line length restriction are opposing each other.

There are two ways out:
1. Putting everything into a separate function. A possibility, but maybe not nice for 1-line-statements.
2. Using shorter variable names, which is also not up to good code standards, as variable name should be self-explanatory.

Both approaches are code-obfuscating, only due to the 79 characters limit. So please, let's increase that.

**Comment by dweindl** [comment]
> let's leave it at 79.

Agreed.

> it allows for windows side-by-side

This is a very strong argument

> we have many nested loops and if's, hence indentations

Think of it as an additional motivation to reduce nesting

> If now an "if"-statements starts at column 21

... then something went wrong in the surrounding code...

**Comment by paulstapor** [comment]
Just found out there's a PEP 8 conformal way of over-indenting in that case. ;) :D
