### ISSUE TITLE
Define objective API more clearly

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#344]
I feel like both of these options aren't realistically used by anybody and bloat the objective code. Moreover having function calls that don't have a value for FVAL are currently not compatible with `objective.history.OptimizerHistory`.

**Comment by yannikschaelte** [comment]
I think these were initially introduced to allow calling an objective function as efficiently as possible (prob. not necessary as higher derivatives are always more expensive). In particular it as used in order to be able to call AMICI easily, specifying in one method what sensis to use.
I think it should be possible to rewrite AmiciObjective without these two things and still not computing unnecessary derivatives. Then, one would need to write separate functions for fun, grad, hess, res, sres, which all set sensis and then call one amici call function, restricting the output accordingly afterwards.

**Comment by FFroehlich** [comment]
Maybe I wasn't clear enough. I would argue that we should remove https://github.com/ICB-DCM/pyPESTO/blob/f74b4d0b54b2f159260664284da5e49709a8245a/pypesto/objective/objective.py#L298 and following as well as https://github.com/ICB-DCM/pyPESTO/blob/f74b4d0b54b2f159260664284da5e49709a8245a/pypesto/objective/objective.py#L363 and following, such that `fun` and `res` always have to accept sensi orders. This shouldn't impact the functionality you described since all of that logic is now implemented in AmiciCalculator, right?

**Comment by yannikschaelte** [comment]
> Moreover having function calls that don't have a value for FVAL are currently not compatible with objective.history.OptimizerHistory.

What is the exact problem? Function calls that only have e.g. gradient would still be possible.

**Comment by yannikschaelte** [comment]
> Maybe I wasn't clear enough. I would argue that we should remove
> 
> https://github.com/ICB-DCM/pyPESTO/blob/f74b4d0b54b2f159260664284da5e49709a8245a/pypesto/objective/objective.py#L298
> 
> and following as well as
> https://github.com/ICB-DCM/pyPESTO/blob/f74b4d0b54b2f159260664284da5e49709a8245a/pypesto/objective/objective.py#L363
> 
> and following, such that `fun` and `res` always have to accept sensi orders. This shouldn't impact the functionality you described since all of that logic is now implemented in AmiciCalculator, right?

Ah, you mean make it the default that fun and res accept sensi orders. I am not sure about that. I would like to be able to write `Objective(fun)` where fun is just a function `x -> fval(x)` and do optimization on that. So yes, AmiciObjective / AmiciCalculator self-implements the logic, but if we use non-amici objectives, these alternatives allow to easily specify any type of objective. Other optimization methods also allow these cases, e.g. grad=bool etc.

**Comment by FFroehlich** [comment]
> > Moreover having function calls that don't have a value for FVAL are currently not compatible with objective.history.OptimizerHistory.
> 
> What is the exact problem? Function calls that only have e.g. gradient would still be possible.

What about optimizers that never call a function that explicitely returns FVAL such as the least squares solvers. I imagine one could end up in a similar situation optimizers that don't perform linesearch such as SGD type optimizers.

https://github.com/ICB-DCM/pyPESTO/blob/4e594d540bb82ec380b784a0b4b68057a497652e/pypesto/objective/history.py#L907

will be all nan and have no minimum.

https://github.com/ICB-DCM/pyPESTO/blob/4e594d540bb82ec380b784a0b4b68057a497652e/pypesto/objective/history.py#L875

will never be true and we fail to retun a minimum.

**Comment by FFroehlich** [comment]
> > Maybe I wasn't clear enough. I would argue that we should remove
> > https://github.com/ICB-DCM/pyPESTO/blob/f74b4d0b54b2f159260664284da5e49709a8245a/pypesto/objective/objective.py#L298
> > 
> > and following as well as
> > https://github.com/ICB-DCM/pyPESTO/blob/f74b4d0b54b2f159260664284da5e49709a8245a/pypesto/objective/objective.py#L363
> > 
> > and following, such that `fun` and `res` always have to accept sensi orders. This shouldn't impact the functionality you described since all of that logic is now implemented in AmiciCalculator, right?
> 
> Ah, you mean make it the default that fun and res accept sensi orders. I am not sure about that. I would like to be able to write `Objective(fun)` where fun is just a function `x -> fval(x)` and do optimization on that. So yes, AmiciObjective / AmiciCalculator self-implements the logic, but if we use non-amici objectives, these alternatives allow to easily specify any type of objective. Other optimization methods also allow these cases, e.g. grad=bool etc.

How about moving that functionality to a separate class such as `FunctionObjective` that performs all of this wrapping for you?

**Comment by yannikschaelte** [comment]
> > Ah, you mean make it the default that fun and res accept sensi orders. I am not sure about that. I would like to be able to write `Objective(fun)` where fun is just a function `x -> fval(x)` and do optimization on that. So yes, AmiciObjective / AmiciCalculator self-implements the logic, but if we use non-amici objectives, these alternatives allow to easily specify any type of objective. Other optimization methods also allow these cases, e.g. grad=bool etc.
> 
> How about moving that functionality to a separate class such as `FunctionObjective` that performs all of this wrapping for you?

No opinion here. Objective code seems quite stable at the moment, so I wouldn't touch it, but if you think moving to a separate class without breaking the API too much makes sense, welcome.

**Comment by yannikschaelte** [comment]
> What about optimizers that never call a function that explicitely returns FVAL such as the least squares solvers. I imagine one could end up in a similar situation optimizers that don't perform linesearch such as SGD type optimizers.
> 
> https://github.com/ICB-DCM/pyPESTO/blob/4e594d540bb82ec380b784a0b4b68057a497652e/pypesto/objective/history.py#L907
> 
> will be all nan and have no minimum.
> 
> https://github.com/ICB-DCM/pyPESTO/blob/4e594d540bb82ec380b784a0b4b68057a497652e/pypesto/objective/history.py#L875
> 
> will never be true and we fail to retun a minimum.

Agreed that we have to change what happens when OptimizerHistory does not contain valid points, this is a :bug: **bug**. For least squares solvers we had the CHI2 values replacing FVAL for this reason, but may be better to just fill in nothing in that case for FVAL, as you suggested. 

True that e.g. SGD may never evaluate any function values. One suggestion would be that the correct thing to do in such cases is **just to return whatever the employed optimizer gives us** as parameter, **potentially with empty FVAL** in that case. This would fit to the proposed behavior of SciPy recently discussed here https://github.com/scipy/scipy/issues/12111 (following up on #327). 

We could also **force the objective function to always be able to compute function values**. Wrapping the objective in such a way that these are always returned could lead to performance losses for some objectives (e.g. if computing the gradient and fval are completely different function calls), therefore one might only do that in `fill_result_from_objective_history`, **evaluating the function once more at the optimal point**.

**Comment by yannikschaelte** [comment]
Opinions? :grin:

**Comment by paulstapor** [comment]
I'm not sure whether I get the problem completely, but here's what I think to understand:
*The question is, which values should be reported in the optimizer history: also all values or only the best value from line-search?"
Is it about that?

If so, personally I think there are reasons for both. But I would rather tend to only store how often the OF was called in line-search. I'm not sure we really also want OF values, parameter vectors, gradients, Hessians, ... from non-accepted steps...
However, also having those values might help in debugging, if an optimizer does not react properly upon inf or NaN values in OF, gradient or Hessian...

**Comment by yannikschaelte** [comment]
> > > Ah, you mean make it the default that fun and res accept sensi orders. I am not sure about that. I would like to be able to write `Objective(fun)` where fun is just a function `x -> fval(x)` and do optimization on that. So yes, AmiciObjective / AmiciCalculator self-implements the logic, but if we use non-amici objectives, these alternatives allow to easily specify any type of objective. Other optimization methods also allow these cases, e.g. grad=bool etc.
> > 
> > 
> > How about moving that functionality to a separate class such as `FunctionObjective` that performs all of this wrapping for you?
> 
> No opinion here. Objective code seems quite stable at the moment, so I wouldn't touch it, but if you think moving to a separate class without breaking the API too much makes sense, welcome.

I agree that it would be nice to be able to rely only on functions that return precisely what was asked for. The "Objective" function is kind of supposed to do exactly that, i.e. translate from arbitrary fun, grad, res, sres, hess to one interface accepting sensi_orders, mode. I think thus fun, res, ... should be regarded as private class attributes. One could use a FunctionObjective for that, not sure. 

One problem in the current implementations may be that AggregatedObjective currently directly uses the fun, grad, ... attributes. Regarding the other problem with the OptimizerHistory, I am not sure if I see the connection yet totally ...

**Comment by yannikschaelte** [comment]
> I'm not sure whether I get the problem completely, but here's what I think to understand:
> *The question is, which values should be reported in the optimizer history: also all values or only the best value from line-search?"
> Is it about that?

I think the point here is rather about "what to do when the optimizer never explicitly asks for function values", like LS or maybe SGD. Then, history.fval_min would always be None, so that in OptimizerHistory currently we have no value at all. However, we use the history to overwrite whatever we get from the optimizer currently, so our result would only contain Nones. Thus, the two options (I think) are to either in every function call return a function value, or to use as best parameter directly what the optimizer gives.

[Remark: Two discussions in one thread ... :grimacing: ]

**Comment by paulstapor** [comment]
> I think the point here is rather about "what to do when the optimizer never explicitly asks for function values", like LS or maybe SGD. Then, history.fval_min would always be None, so that in OptimizerHistory currently we have no value at all. However, we use the history to overwrite whatever we get from the optimizer currently, so our result would only contain Nones. Thus, the two options (I think) are to either in every function call return a function value, or to use as best parameter directly what the optimizer gives.

Well... fair enough that, for example, SGD will not return objective function values, but only stochastic estimates for those (and is in fact even incapable of return full OF values). Taking the best OF value from the trace does really not make any sense here and may in fact even be harmful, because what you will get will be just the strongest outlier of these estimates, but unlikely to be the best parameter vector.

An option which can be included for yet creating waterfall plot for SGD optimizations would be a postprocessing step, which computes (only) the OF on the full dataset once after optimization. This is e.g. done in parPE (and increases computation time by about 1% while greatly increasing interpretability).

Such an action might be an option for other optimizers as well, but pretty much just amounts to "just using whatever the optimizer gives us".
However, it might yield a more correct OF value: Optimizers which use a penalization (such as interior-point) might only report the penalized OF value instead the true one... Also in this case, a "postevaluation" would make sense...

Overall, the trace thing might be more powerful (allows to also find values which are better than the final one), but might not always work...
Include a flag, which one to do, and make that flag optimizer dependent?
Do both (re-evalute best found OF value from trace vs. re-evaluated last value), compare, take best? Idelaly with a flag disabling the history comparison, due to possibly including SGD type optimizers?
Would be the most comprehensive, but also blow up the code...

> [Remark: Two discussions in one thread ... 😬 ]

Yep...

**Comment by FFroehlich** [comment]
Okay, lets focus this discussion. In this issue I want to address the issue of the objective API not being clearly defined (changed name accordingly). Although it may seem pretty stable, there continuously are small (probably inadvertant) changes to it that break stuff in all kinds of places.

Maybe we can replace the current implementation of dict(tuple) with a class that ensures API is adhered to centrally, unittest that once, fix all stuff that is related to it and no longer need all those regression tests, which are currently missing but would tell us whats broken.

What to do with an optimizer that doesn't return an `FVAL` is something to keep in mind, but not the primary thing that I want to address here. Also, I am more worried about the least-squares solvers than anything SGD.

**Comment by yannikschaelte** [comment]
> Maybe we can replace the current implementation of dict(tuple) with a class that ensures API is adhered to centrally, unittest that once, fix all stuff that is related to it and no longer need all those regression tests, which are currently missing but would tell us whats broken.

you mean the output of `__call__`?

I would say that `__call__` should be the only way of calling an Objective (except conveniences like get_grad, ...); fun/... are to be considered private. If we can get AggregatedObjective to work on that, this would resolve many problems already I think.

**Comment by FFroehlich** [comment]
> > Maybe we can replace the current implementation of dict(tuple) with a class that ensures API is adhered to centrally, unittest that once, fix all stuff that is related to it and no longer need all those regression tests, which are currently missing but would tell us whats broken.
> 
> you mean the output of `__call__`?
> 
> I would say that `__call__` should be the only way of calling an Objective (except conveniences like get_grad, ...); fun/... are to be considered private. If we can get AggregatedObjective to work on that, this would resolve many problems already I think.

Yes, and that would be substantially easier if it wouldn't be the wild west in terms of what those functions can potentially return.

**Comment by yannikschaelte** [comment]
If AggregatedObjective does not use fun/grad/..., it does not have to care about this anymore, right? The purpose of an Objective is to precisely map all those input functions types (bools, tuples, ...) to one objective function type, so we won't get rid of that.

I could imagine sth like
```python
def AggregatedObjective::__call__(x, sensi_orders, mode):
    # potentially some preprocessing
    vals = [obj(x, sensi_orders, mode) for obj in self.objectives]
    # aggregate vals
    # potentially some postprocessing
```

**Comment by FFroehlich** [comment]
> If AggregatedObjective does not use fun/grad/..., it does not have to care about this anymore, right? The purpose of an Objective is to precisely map all those input functions types (bools, tuples, ...) to one objective function type, so we won't get rid of that.
> 
> I could imagine sth like
> 
> ```python
> def AggregatedObjective::__call__(x, sensi_orders, mode):
>     # potentially some preprocessing
>     vals = [obj(x, sensi_orders, mode) for obj in self.objectives]
>     # aggregate vals
>     # potentially some postprocessing
> ```
 Nope, not possible since replacing call remove replace all the pre and postprocessing functionality that is currently implemented in `Objective` and e.g. the history object will only be attached to the aggregate objective, not all the children.

**Comment by FFroehlich** [comment]
It should be possible to do it at the level of `_call_unprocessed` though.

**Comment by yannikschaelte** [comment]
yes, I was thinking about implementing the pre/postprocessing here as well. but going via he "unprocessed" functions makes much more sense (probably should make those public then)

**Comment by FFroehlich** [comment]
> It should be possible to do it at the level of `_call_unprocessed` though.

I'm still not 100% sure whether that fixes everything surrounding the `fun_accept_sensi_orders` variables though etc or whether those have to be still set in the aggregate objective. As soon as they are used anywhere else in Objective, the AggregateObjective would break again, thats why I would prefer if all the logic in `_call_mode_fun` and `_call_mode_res` is handled in a derived class and.

**Comment by yannikschaelte** [comment]
I would say this is handled in #387
