### ISSUE TITLE
Waterfall plot for multiple results depend on order of result list

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#382]
When providing a list of pyPESTO optimization results to the waterfall routine, I get qualitatively different plots depending on the order of the results.

My best guess is, that this is a problem in offsetting the different results when plotting in `log10` scale. If the first result in the list does not find the overall best value, it is still offsetted to 1. If the next result contains a better value, a different offset is used, which makes the waterfall plots not comparable anymore.

**Comment by paulstapor** [comment]
Thanks for the hint concerning the offset. Will look into that!

**Comment by paulstapor** [comment]
Thanks, there is definitely a bug in the plotting, because the offset computation is just wrong...
It really also gives incorrect results in some cases (only if plotting lists of results)... Wow. Things are better when plotting in linear scale, but still not the way I want them to be...
Fixing it...

**Comment by paulstapor** [comment]
Was already resolved, just not closed upon PR
