### ISSUE TITLE
Start points from history

### ISSUE THREAD

**Issue by plakrisenko** [ICB-DCM/pyPESTO#487]
Add possibility to choose start points from a history file or a folder with history files. 

Would it be better to do it via setting `x_guesses` (#445 should be implemented) or via `startpoint_method` (maybe something along these lines https://github.com/ICB-DCM/pyPESTO/commit/e1d3c3ffcc9ad09df4c467ddf06e28875600b3fa)?

**Comment by FFroehlich** [comment]
`x_guesses` is intended for static starting points, while `startpoint_method` is intended to generate them dynamically (which could be sampling from a limited pool). I think both can make sense, but I would argue that `x_guesses` seems more appropriate since the number of possible starts points is indeed finite and the function that sets `x_guesses` can probably provide more fine-grained filtering than what is possible with `startpoint_method`.

**Comment by plakrisenko** [comment]
Thank you for the explanation!
In this case, it probably makes more sense to fix #445 and implement #259. Then one can just use `OptimizeResult.get_for_key`.

**Comment by dweindl** [comment]
> In this case, it probably makes more sense to fix https://github.com/ICB-DCM/pyPESTO/issues/445 and implement https://github.com/ICB-DCM/pyPESTO/issues/259.

Both done, right?
