### ISSUE TITLE
res_to_fval is not doing the right conversion

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#56]
`fval` from amici objective also includes the log(sigma) summand (which is necessary for cases where sigma is parameter dependent).

**Comment by yannikschaelte** [comment]
res_to_fval is, i think, only used as a comfort function in case one does lsqnonlin optimization, so that the fvals which are internally optimized in the optimization algorithm based on residuals, are also returned in the trace and result object. is it possible to use redisual-based algorithms with parameter-dependent sigma?

**Comment by FFroehlich** [comment]
There is a trick to also formulate problems with parameter dependent sigmas as purely residual, but thats not the main point why I want this. 

I think we will run into trouble down the road if `fval` values are not comparable across optimization algorithms, especially when comparing/mixing results from multiple optimizers. I don't think its so important for the traces, which is why I recommend storing `chi2` instead of `fval` for those, but for the final `fval` that is reported, I think calling `get_fval` when finalizing the results should not be too much of an issue.

**Comment by FFroehlich** [comment]
Meh, `Objective` instance is not available from within the `ObjectiveHistory` instance ...

**Comment by yannikschaelte** [comment]
now is
