### ISSUE TITLE
ERROR: Could not build wheels for amici which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by stephanmg** [ICB-DCM/pyPESTO#683]
Hi developers,

this might be an easy one to fix:

I'm facing the following error message when executing `tox -e base`:
`Could not build wheels for amici which use PEP 517 and cannot be installed directly.`

I followed the steps described on  https://pypesto.readthedocs.io/en/latest/contribute.html  (I am on the develop branch).

Cheers!

**Comment by yannikschaelte** [comment]
Hi @stephanmg , the problem here is likely that AMICI has various external dependencies (as have other test tools, e.g. ipopt), which need to be separately installed on the test system. All external dependencies can be found here https://github.com/ICB-DCM/pyPESTO/blob/main/.github/workflows/install_deps.sh (`bash .github/workflows/install_deps.sh amici [...]`), used e.g. on github actions in https://github.com/ICB-DCM/pyPESTO/blob/main/.github/workflows/ci.yml#L12. I guess we should document this more properly.

As the AMICI installation may be dependent on your system, full instructions can be found here: https://github.com/AMICI-dev/AMICI/blob/master/INSTALL.md

**Comment by stephanmg** [comment]
@yannikschaelte I see, thanks for the clarification. Yes, then perhaps it would be great to add this information to the docs.
