### ISSUE TITLE
Addition in parameter estimation

### ISSUE THREAD

**Issue by Georacer** [ICB-DCM/pyPESTO#77]
Hello!

We recently had some research done on parameter estimation in non-gaussian processes, targeted for aerodynamics models of fixed-wing UAVs.
(c.f. https://www.researchgate.net/publication/325284594_On-line_Aerodynamic_Model_Identification_on_Small_Fixed-Wing_UAVs_with_Uncertain_Flight_Data)
We used a variation of the Generalized Total Least Squares algorithm.

I intend to write a Python library, but first I tool a look at pip for similar packages.
Yours was one of the results.
My question is whether you believe that this project could be a good starting point for implementing our algorithms or it's too foreign to what I want to achieve and I'd be better off starting fresh.

Thank you for your time,
George

**Comment by paulstapor** [comment]
Hi George,

sorry the late answer.
We have/had a more mature toolbox in MATLAB (PESTO) and are now transferring the main functionality (and hopefully more) to Python. So, right now, the toolbox is by far not as powerful as we want it to be and maybe not the most user-friendly thing, but it is supposed to grow quickly.

Currently, most of the optimizers from SciPy can be used in a multi-start setting, so pyPESTO supports multi-start local optimization (in a gradient-based fashion). Depending on your experience with optimization methods in your specific field, our approach can be advantageous, but it doesn't have to be (there's no free lunch...).
So, if you know that for your application multi-start local (gradient-based) optimization is a good thing, then pyPESTO may be worth a shot. If you think you're better off using genetic algorithms, swarm-based approaches, simulated annealing or some simplex-method, then pyPESTO (at least in it's current state) is probably not what you want to go for... If you're not sure, the pyPESTO can still be worth it, since it's our aim to have it as simple and user-friendly as possible...

Best,
Paul

**Comment by Georacer** [comment]
I'm glad I asked, because it was most likely that I hadn't understood what your package really does.

Our algorithm, at its core uses recursive SVD for parameter estimation, not a gradient-based algorithm.
That said, I think there would be core differences between our approaches.

Thank you for your time!
