### ISSUE TITLE
Issue using MultiProcess engine

### ISSUE THREAD

**Issue by LarkinIt** [ICB-DCM/pyPESTO#950]
Hi,

I am currently working on a mechanistic model of alphavirus replication encoded in BioNetGen language. For preliminary model construction and analysis, I ended up using the `libroadrunner` package to load and simulate the model in Python from an SBML file. Now, I am trying to utilize pyPESTO to calibrate my model to experimental data as well as some semi-quantitative heuristics. I was successful in setting up everything and run some basic, short test runs in a Jupyter notebook using pyPESTO. However, when I try to parallelize using MultiProcess, I get a weird error message that I have been unable to resolve. I attached images of the general code flow and the error traceback.

**Bug description**
The error occurs when trying to pass `MultiProcessEngine` object to `optimize.minimize()`.
Error traceback:
![image](https://user-images.githubusercontent.com/36136447/195154207-a54e16c1-6fe6-4dfb-b953-c5e79d953d83.png)

**To reproduce**
General code flow:
![image](https://user-images.githubusercontent.com/36136447/195153569-69b581f1-1e3b-42ef-916c-667cdf3e5434.png)

**Things I have tried to resolve error**
- Implemented model using AMICI instead of libroadrunner
- Tried on the department cluster instead of local machine
- Run in a python script instead of a Jupyter notebook

**Environment**
- Operating system: Ubuntu 20.04 
- `pypesto` version: 0.2.13
- `amici` version: 0.13.0
- `libroadrunner` version: 2.0.5 
- Python version: 3.9.12

Thanks!
Caroline Larkin

**Comment by yannikschaelte** [comment]
Hi @LarkinIt , in order to parallelize, the MultiProcessEngine needs to copy the problem over to other threads, which is performed by "pickling" in Python. While most Python-only objects are usually pickleable out of the box, this gets trickier for other objects, which may then need to implement own `__getstate__` and `__setstate__` methods. If you use AMICI via the `AmiciObjective`, it should be pickleable already. For tellurium, we have currently no such wrapper. If you need to use a custom AMICI based objective not based on `AmiciObjective`, or another simulation framework, the AmiciObjective implementation of said methods https://github.com/ICB-DCM/pyPESTO/blob/develop/pypesto/objective/amici/amici.py#L252 may still be useful (which essentially recreate the problem from file).

**Comment by LarkinIt** [comment]
Hi @yannikschaelte I found the issue after some digging. The issue lies with the version of `libroadrunner` and has nothing to do with pyPESTO or AMICI. 

![Screenshot from 2022-10-11 16-33-52](https://user-images.githubusercontent.com/36136447/195193160-fe290b78-1638-4762-bd52-585b2454a106.png)


Thank you for the helpful explanation and my apologies for wasting your time. 

Thanks,
Caroline
